spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: HOME-PAGE
          uri: http://localhost:8081
          predicates:
            - Path=/hview/**
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: 'gateway,health,info'
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
server:
  port: 8989