spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name : movie-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled : false
eureka:
  client:
    service-url:
      defaultzone : http://localhost:8761/eureka/
server:
  port: 8001
logging:
  level:
    org.springframework.security: DEBUG  # Set log level to DEBUG for Spring Security

