spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: cassandra-db
  data:
    cassandra:
      secure-connect-bundle: ${BUNDLE_PATH}
      keyspace-name: ${CASSANDRA_KEYSPACE}
      username: ${CASSANDRA_USERNAME}
      password: ${CASSANDRA_PASSWORD}
      local-datacenter: ${CASSANDRA_DATACENTER}
      request:
        timeout: ${CASSANDRA_REQUEST_TIMEOUT}
      connection:
        connect-timeout: ${CASSANDRA_CONNECTION_TIMEOUT}
        init-query-timeout: ${CASSANDRA_INIT_QUERY_TIMEOUT}

datastax:
  astra:
    secure-connect-bundle: ${BUNDLE_PATH}

astra:
  db:
    id: ${ASTRA_DB_ID}
    region: ${ASTRA_DB_REGION}
    keyspace: ${ASTRA_DB_KEYSPACE}
    application:
      token: ${ASTRA_DB_TOKEN}

server:
  port: 8081